### PR TITLE
Feature/MQ2mzTab

### PR DESCRIPTION
**Pull request by MFreidank**
This branch adds a tool that converts between `MaxQuant`results to `mzTab` as used by `OpenMS`. 

Note: The tool has a dependency called `tidyr`, installation can be done simply from inside `R`:
`install.packages(tidyr)`

Note2 (29.06.2018): This is only a beta version and likely to support only parts of the entire feature set. It currently also only supports only labeled analyses (tmt is not supported yet). 

Any suggestions/remarks/bug reports are very welcome.

### CODE REVIEW

**Comment by lars20070** [comment]
Guess `example_1/2/3` can go.

**Comment by lars20070** [comment]
On `allPeptides.txt` you can find the name of the original i put file. `AGA150` in your example. Let's name the output like this, i.e. `AGA150.mzTab`. If there are more than one input file (label free) then please `AGA150_etal.mzTab`.

**Comment by lars20070** [comment]
For this task, I see no good reason to use any libs (`tidyr`, `dplyr`).
Will only complicate maintenance and support.

**Comment by lars20070** [comment]
`sh/bat` scripts still missing, see #9. Same approach as for the reports, e.g. `mzTab2report`.

**Comment by MFreidank** [comment]
@lars20070 I already removed the unused files. I will address the remaining issues over the weekend.

**Comment by MFreidank** [comment]
sh/bat scripts are added now. Linux and mac script tested successfully (could potentially be a single script). 
Input file renaming (`AGA150` and `AGA150_etal`) is also done. 
I also added documentation and some input sanitization (does maxquant folder exist? does maxquant folder contain all files we expect?). 
Notes:
- So far we only support Labeled analyses (Columns Intensity.L and Intensity.H and optionally additional column Intensity.M), TMT support is part of our next steps.
- Currently our output mzTab is written to the current working directory -- we may want to write it elsewhere (e.g. in the input folder containing MaxQuant files?)
- Modifications are not yet parsed (this should also be done in the next steps).
- This script is still largely untested and has only been tried on a single script (we might want to add tests and use a validator)

**Comment by lars20070** [comment]
@MFreidank Thanks for the changes.

- Please add support for TMT and label free.
- Please write the output next to the MaxQuant directory.
- Leave the mod column out for now.
- Please test with `mzTab` validator and `mzTab2report` on our server.

**Pull request merged**
